@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Skill {
    - String name

    + Skill(name)
    - validateSkill(Skill)
}

class RegisterSkillController {

    + RegisterSkillController()
    + registerSkill(name)
}

class RegisterSkillUI {
}

class Collaborator {
    -String name
    -Date dateOfBirth
    -Date admissionDate
    -Address address
    -int phoneNumber
    -String email
    -int cc
    -int cardNumber

    + Collaborator(name, dateOfBirth, admissionDate, address, phoneNumber, email, cc, cardNumber)
}

class Address{
    -String streetName
    -String postCode
    -int doorNumber

    +Address(streetName, postCode, doorNumber)
}

class HumanResourcesManager {
}

class Repositories {

    - Repositories()
    + getInstance() : Repositories
    + getSkillRepository()
}

class skillRepository {
    - ArrayList Skill

    - addSkill(Skill)
    - validateSkill(Skill)
    + createSkill(name)
}

RegisterSkillController .> Repositories : repositories
RegisterSkillUI .> RegisterSkillController
Repositories -> Repositories : instance
Repositories --> "1" skillRepository : skillRepository
skillRepository "1" --> "*" Skill : Skill
Collaborator  <|--  HumanResourcesManager
RegisterSkillController ..> "1" HumanResourcesManager : HumanResourcesManager
HumanResourcesManager <--  Skill: createdBy
Collaborator "*" --> "*" Skill : skills
Address "1" --> "*" Collaborator : address


@enduml