@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model - US03 Register a collaborator

class HumanResourceManager {
}

class Collaborator {
    name
    dateOfBirth
    admissionDate
    address
    phoneNumber
    email
    cc
    cardNumber
}

class Job{
    name
}

class Address{
    streetName
    postCode
    doorNumber
}

Collaborator  <|---  HumanResourceManager
HumanResourceManager "1" --- "1..*" Collaborator : Registers >
Collaborator "1..*" - "1" Job : Has >
Address "1" - "1..*" Collaborator : < lives


@enduml