@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US05 - Generate team

autonumber

actor "Human Resources Manager (HRM)" as HRM
participant ":GenerateTeamUI" as UI
participant ":GenerateTeamController" as CRL
participant "team\n:Team" as TEAM


activate HRM
    'Interações com UI
            HRM -> UI : asks to generate a new proposals teams
    activate UI

            UI --> HRM : requests data (team max size,team min size, skills number size)
    deactivate UI

            HRM -> UI : types requested data
    activate UI
        loop skill number size

            UI --> HRM : requests data (skillName)

    deactivate UI

            HRM -> UI : insert a skill name

    activate UI

            UI -> CRL : hasSkillByName(skillName)
            ref over CRL
                has Skill By Name
            end ref

            activate CRL


                   CRL --> UI : true/false

            deactivate CRL

    end loop




            UI --> HRM : shows all data and requests confirmation
    deactivate UI

            HRM -> UI : confirms data
    activate UI

            UI -> CRL : generateTeams(minSize,maxSize,skillList)

            activate CRL

                CRL -> CRL : getCollaboratorBySkill(skillList)

                ref over CRL
                    Get Collaborator By Skill
                end ref
                                activate CRL

                                CRL --> CRL : collaboratorList

                                deactivate CRL

                                'Generate Teams Method

                               loop Proposal Team List

                               CRL -> TEAM** : create(minSize,maxSize,collaboratorList,skillList)
                               activate TEAM
                                   TEAM ->TEAM : validateTeam(team)

                                   TEAM --> CRL : team

                               deactivate TEAM
                               end
                                CRL --> UI : teamsList

                            deactivate CRL


            deactivate CRL

            UI --> HRM : shows the list of the team's proposals and asks you to choose one of them

    deactivate UI

            HRM -> UI : choose one of the proposals and confirms


    activate UI

            UI -> CRL : registerProposalTeam(team)

            ref over CRL
                Register Proposal Team
            end ref

            activate CRL



                CRL--> UI : team
            deactivate CRL

            UI --> HRM : displays operation success

    deactivate UI
@enduml