@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class GenerateTeamController {
    + GenerateTeamController()
    - getAllSkillsByName(skillListNames)
    - getCollaboratorBySkill(skillList)
    - generateProposalTeamList(minSize,maxSize,skillList,collaboratorList)
    + getSkillList()
    + generateProposalTeams(minSize,maxSize,skillList)
    + registerProposalTeam(team)
}

class Team {
    - List<Collaborator> collaboratorList
    + Team(collaboratorList)
}

class GenerateTeamUI {
}

class Collaborator {
    -String name
    -List<Skill> skillList
    -Job job
    -Date dateOfBirth
    -Date admissionDate
    -Address address
    -String phoneNumber
    -String email
    -Document document

    + Collaborator(name, job, dateOfBirth, admissionDate, address, phoneNumber, email, document)
    + hasCollaboratorSkill(skill)
}


class HumanResourcesManager {
}

class Repositories {

    - Repositories()
    + getInstance() : Repositories
    + getTeamRepository()
    + getCollaboratorRepository()
    + getSkillRepository()
}

class TeamRepository {
    - List <Team> teamList
    - addTeam(team)
    - addListTeamProposal(teamListProposal,team)
    - removeCollaboratorList(collaboratorList,team)
    - addIdealCollaboratorList(idealCollaboratorList, collaborator)
    + registerProposalTeam(team)
    + generateProposalTeamList(maxSize,skillList,collaboratorList)
}

class SkillRepository {
    - List <Skill> skillList
    + getSkillList()
    + getSkillByName(skillName)
}

class CollaboratorRepository {
    - List <Collaborator> collaboratorList
    + getCollaboratorsBySkill(skillList)
}

class HumanResourcesManager{}

GenerateTeamController .> Repositories : repositories

GenerateTeamUI .> GenerateTeamController
Repositories -> Repositories : instance

Repositories --> "1" TeamRepository
Repositories --> "1" SkillRepository
Repositories --> "1" CollaboratorRepository

TeamRepository ---> "*" Team : team
CollaboratorRepository ---> "*" Collaborator : collaborator

GenerateTeamController ...> TeamRepository
GenerateTeamController ...> SkillRepository
GenerateTeamController ...> CollaboratorRepository
GenerateTeamController .> Collaborator
GenerateTeamController .> Team

Collaborator  <|-- HumanResourcesManager

HumanResourcesManager "1" --> "1..*" Team : defines
Collaborator "1..*" --> "1" Team : contains



@enduml