@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":GenerateTeamController" as CRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository\n:CollaboratorRepository" as CL
participant "collaborator\n:Collaborator" as Collaborator


autonumber 13
--> CRL: getCollaboratorsBySkill(skillList)

autonumber 13.1

activate CRL
group Get Collaborator By Skill

CRL -> REP : getInstance()
activate REP

REP --> CRL : repositories

deactivate REP

CRL -> PLAT : getCollaboratorRepository()
activate PLAT

PLAT --> CRL : collaboratorRepository

deactivate PLAT

CRL -> CL : getCollaboratorsBySkill(skillList)
activate CL
loop skillList

CL -> Collaborator : hasCollaboratorSkill(skill)
activate Collaborator


Collaborator -> CL : true/false
end
deactivate Collaborator
CL--> CRL : collaboratorList

deactivate CL

end
autonumber 14

<--CRL : collaboratorList
deactivate CRL

@enduml