@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - US04 - Assign Skills

autonumber

'hide footbox
actor "Human Resources Manager (HRM)" as HRM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository\n:SkillRepository" as SR
participant "collaboratorRepository\n:CollaboratorRepository" as CL
participant "collaborator\n:Collaborator" as Collb


activate HRM

        HRM -> UI : asks to assign one or more skill to a collaborator
    activate UI
UI -> CTRL : getCollaboratorList(name)
activate CTRL

ref over CTRL
Get Collaborator List
end

deactivate Collb

CTRL--> UI : collaboratorList

deactivate CTRL

UI <-- HRM : show collaborator list and asks to select

  UI -> CTRL :getSkillList()
  activate CTRL
  ref over CTRL
  Get Skill List
  end
  CTRL -> UI : skillList

  deactivate CTRL

    loop skill number size
HRM -> UI : chose one of collaborator to add skill, from collaboratorlist()
HRM -> UI : types requested data
end loop

activate UI

deactivate CTRL



deactivate CTRL



        UI --> HRM : displays the data and requests confirmation

deactivate UI

        HRM -> UI : confirms and submits data

activate UI


         UI -> CTRL: assignSkill(collaborator, skill)

        activate CTRL
        ref over CTRL
        Assign Skill Collaborator
        end


            CTRL --> UI : collaborator
      deactivate CTRL

      UI --> HRM : displays operation success
    deactivate UI
deactivate HRM
@enduml