@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Skill {
    - String name
    - validateSkill(Skill)
    + Skill(name)
}

class AssignSkillController {

    + AssignSkillController()
    + assignSkill(name)
    + AssignSkillCollaborator(collaborator,skill)
    + getCollaboratorList(name)
    + skillListAdd(skill)
    + getSkillList(skillListName)
}

class AssignSkillUI {
}

class Collaborator {
    -String name
    -List<Skill> skillList
    -Job job
    -Date dateOfBirth
    -Date admissionDate
    -Address address
    -String phoneNumber
    -String email
    -int cc
    -int taxpayer

    + Collaborator(name, dateOfBirth, admissionDate, address, phoneNumber, email, cc, taxpayer)
    +skillListAdd(Skill)
}

class HumanResourcesManager {
}

class Repositories {

    - Repositories()
    + getInstance() : Repositories
    + getSkillRepository()
}

class SkillRepository {
    - List <Skill> skill
    - validateSkill(Skill)
    - skillListAdd(skill)
    - getSkillList(skillListName)

}

AssignSkillController .> Repositories : repositories
AssignSkillUI .> AssignSkillController
Repositories -> Repositories : instance
Repositories --> "1" CollaboratorRepository : CollaboratorRepository
Repositories --> "1" SkillRepository : SkillRepository
SkillRepository "1" --> "*" Skill : skill
Collaborator  <|--  HumanResourcesManager
AssignSkillController ..> Skill
AssignSkillController ..> SkillRepository

HumanResourcesManager <--  Skill: AssignBy
Collaborator "*" --> "*" Skill : has
Collaborator .> CollaboratorRepository : collaboratorRepository

class CollaboratorRepository {

+getCollaboratorList(name)
+AssignSkillCollaborator(collaborator,skill)
}

@enduml