@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US28 - Consult assigned tasks

autonumber

actor "Collaborator" as Col
participant ":System" as System

activate Col

    Col -> System : asks to consult assigned tasks
    activate System

    System --> Col : requests data(startDate, endDate, status)
    deactivate System

    Col->System: types data
    activate System

    System --> Col : displays the data and requests confirmation
    deactivate System

    Col -> System : confirms data
    activate System

    System --> Col : shows list of assigned tasks
    deactivate System

    System --> Col : displays operation success
    deactivate System

@enduml