@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "brandRepository:\nBrandRepository" as BR
participant "brand:\nBrand" as Brand

autonumber 7
-> CTRL: getBrand(brandName,modelName)

autonumber 7.1
activate CTRL
    group Get Brand Object

    CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getBrandRepository()
            activate PLAT

                PLAT --> CTRL : brandRepository
            deactivate PLAT

        CTRL -> BR : hasBrandByName(brandName)

        activate BR

            BR -> CTRL : true/false
        deactivate BR

        CTRL -> BR : getBrandByModelName(modelName)

        activate BR

        BR -> Brand : hasModelByName(modelName)

        activate Brand

        Brand --> BR : true/false
        deactivate Brand

        BR --> CTRL : brand
        deactivate BR
    end

    autonumber 8
    <-- CTRL : brand
deactivate CTRL


@enduml