@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "brand:\nBrand" as Brand

autonumber 9
-> CTRL: getModel(brand,modelName)

autonumber 9.1
activate CTRL
    group Get Model Object

        CTRL -> Brand : hasModelByName(modelName)

        activate Brand

            Brand --> CTRL : true/false

        deactivate Brand
    end

    autonumber 10
    <-- CTRL : model
deactivate CTRL


@enduml