@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "brandRepository:\nBrandRepository" as BR

autonumber 7
-> CTRL: getBrand(brandName)

autonumber 7.1
activate CTRL
    group Get Brand Object

    CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getBrandRepository()
            activate PLAT

                PLAT --> CTRL : brandRepository
            deactivate PLAT

        CTRL -> BR : hasBrandByName(brandName)

        activate BR

            BR -> CTRL : true/false
        deactivate BR
    end

    autonumber 8
    <-- CTRL : brand
deactivate CTRL


@enduml