@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Brand {
    - String name
    - Arraylist Model model

    + Brand(name)
    + createModel(modelName)
    - addModel(model)
    - validateBrand(brand)
    - validateModel(model)
}

class Model {
    - String name

    + Model(name)
    - validateModel(model)
}

class Vehicle {
    - Brand brand
    - Model model
    - String type
    - float tare
    - float grossWeight
    - int currentKm
    - Date registerDate
    - Date acquisitionDate
    - int checkupFrequency
    - String licensePlate

    + Vehicle(brand,model,type,tare,grossWeight,currentKm,registerDate,acquisitionDate,checkupFrequency,licensePlate)
    - validateVehicle(vehicle)
}

class RegisterVehicleController {

    + RegisterVehicleController()
    - registerBrand(brandName)
    - registerModel(modelName)
    + registerVehicle(brandName,modelName,type,tare,grossWeight,currentKm,registerDate,acquisitionDate,checkupFrequency,licensePlate)
}

class RegisterVehicleUI {
}

class Collaborator {
    -String name
    -Date dateOfBirth
    -Date admissionDate
    -Address address
    -int phoneNumber
    -String email
    -int cc
    -int cardNumber

    + Collaborator(name, dateOfBirth, admissionDate, address, phoneNumber, email, cc, cardNumber)
}

class VehicleFleetManager {
}

class Repositories {

    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
    + getBrandRepository()
}

class vehicleRepository {
    - ArrayList Vehicle vehicle

    - addVehicle(vehicle)
    - validateVehicle(vehicle)
    + createVehicle(brand,model,type,tare,grossWeight,currentKm,registerDate,acquisitionDate,checkupFrequency,licensePlate)
}

class brandRepository {
    - ArrayList Brand brand

    - addBrand(brand)
    - validateBrand(brand)
    + createBrand(brandName)
}

RegisterVehicleController .> Repositories : repositories
RegisterVehicleUI .> RegisterVehicleController
Repositories -> Repositories : instance
Repositories --> "1" vehicleRepository : vehicleRepository
Repositories --> "1" brandRepository : brandRepository
vehicleRepository ---> "*" Vehicle : vehicle
brandRepository --> "*" Brand : brand
Collaborator  <|--  VehicleFleetManager
RegisterVehicleController ..> "1" VehicleFleetManager : VehicleFleetManager
VehicleFleetManager <--  Vehicle: createdBy
Collaborator "*" --> "*" Vehicle : drives
Brand "1" --> "1..*" Model : model
Brand "1" --> "1..*" Vehicle : has
Vehicle "1..*" -> "1" Model : has


@enduml