@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Partial Domain Model US20


class Collaborator {
    name
    dateOfBirth
    admissionDate
    phoneNumber
    taxpayer
    email
}

class GreenSpace {
    name
    localName
    area
}

class Document{
    docType
    number
}

class Address {
    streetName
    postCode
    doorNumber
}


class GreenSpacesManager {
}

class Garden {
}

class MediumPark {
}

class LargePark {
}


Collaborator "1" - "1" Document : has >

Collaborator "1..*" -- "1" Address : lives >

Collaborator  <|--  GreenSpacesManager

GreenSpacesManager "1" -- "*" GreenSpace : register >

GreenSpace <|-- Graden
GreenSpace <|-- MediumPark
GreenSpace <|-- LargePark



@enduml