@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Collaborator {
    name
    dateOfBirth
    admissionDate
    phoneNumber
    taxpayerNumber
    email
}

class Team{
    id
}

class GreenSpace {
    name
    area
}

class TaskAgenda{
    startDate
    expectedDuration
}

class Agenda{
}

class TaskToDoList{
    taskReference
    status
    urgency
    aproxExpectedDuration
}

'-------------Collaborator-------------
Collaborator "1..*" -- "1" Team : Contains <

'-------------GreenSpace-------------
GreenSpace <|-- Garden
GreenSpace <|-- MediumPark
GreenSpace <|-- LargePark

'-------------Task-------------
TaskAgenda "1..*" --- "1" GreenSpace :  Carried out in  >
Team "1" --- "*" TaskAgenda : executed by <
TaskToDoList "1..*" ----- "1" GreenSpace :  Carried out in  >
Agenda "1" -u- "*" TaskAgenda : contains >
TaskAgenda "1" - "1" TaskToDoList : includes >

@enduml
