@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":GenerateTeamController" as CRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as PLAT
participant "teamRepository:\nTeamRepository" as TeamRepository

autonumber 20
--> CRL: registerProposalTeam(team)

autonumber 20.1

activate CRL
group Register Proposal Team

CRL -> REP : getInstance()
activate REP

REP --> CRL : repositories

deactivate REP

CRL -> PLAT : getTeamRepository()
activate PLAT

PLAT --> CRL : teamRepository

deactivate PLAT

CRL -> TeamRepository : registerProposalTeam(team)
activate TeamRepository

TeamRepository -> TeamRepository : addTeam(team)

activate TeamRepository
TeamRepository --> TeamRepository : true/false
deactivate TeamRepository

TeamRepository--> CRL : team

deactivate TeamRepository

end
autonumber 21
<--CRL : team
deactivate CRL

@enduml