@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US06 Register a vehicle

autonumber

actor "Vehicle and Equipment Fleet Manager (VFM)" as VFM
participant ":System" as System

    activate VFM
    VFM -> System : asks to register a vehicle
    activate System


    System --> VFM : requests data (Brand, Model, Type, Tare, Gross Weight, Current Km, \nRegister Date, Acquisition Date, Maintenance/Checkup Frequency, License Plate)
    deactivate System

    VFM -> System : types requested data
    activate System

    System --> VFM : shows all data and asks for confirmation
    deactivate System

    VFM -> System : confirms data
    activate System

    System --> VFM : displays operation success
    deactivate System

@enduml