@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (SD) - US28 - Consult assigned tasks

autonumber

actor "Collaborator" as Col
participant "ConsultAssignedTasksUI" as UI
participant "ConsultAssignedTasksController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "teamRepository\n:TeamRepository" as TeamRepo
participant "team\n:Team" as TEAM
participant "collaborator\n:Collaborator" as Collab
participant "agenda\n:Agenda" as AGENDA
participant "tasksAgenda\n:TasksAgenda" as TASKSAGENDA
participant "taskAgenda\n:TaskAgenda" as TASKAGENDA
participant "taskToDoList\n:TaskToDoList" as TASKToDOList
participant "taskAgendaMapper\n:TeamMapper" as TASKAGENDAMAPPER


activate Col

    Col -> UI : asks to consult assigned tasks
    activate UI

    UI --> Col : requests data(startDate, endDate, status)
    deactivate UI

    Col->UI: types data
    activate UI

    UI --> Col : displays the data and requests confirmation
    deactivate UI

    Col -> UI : confirms data
    activate UI

    UI-> CTRL : getTasksBetweenTwoDates(startDate, endDate, status)
    activate CTRL

        CTRL -> CTRL : getCollaboratorFromSession()
        activate CTRL

            ref over CTRL
                Design in US20
            end ref

        CTRL --> CTRL : collaborator
        deactivate CTRL

    CTRL -> RepositorySingleton: getInstance()
    activate RepositorySingleton

    RepositorySingleton --> CTRL: repositories
    deactivate RepositorySingleton

    CTRL -> PLAT : getTeamRepository()
    activate PLAT

    PLAT --> CTRL : teamRepository
    deactivate PLAT

    CTRL -> TeamRepo : getTeamByCollaborator(collaborator)
    activate TeamRepo

        loop for each team in teamList[in teamRepository]

            TeamRepo -> TEAM : hasTeamByCollaborator(collaborator)
            activate TEAM

            loop for each collaborator in collaboratorList[in Team]
                TEAM -> Collab : isEquals(collaborator)
                activate Collab

                Collab --> TEAM: true/false
                deactivate Collab

            end
                TEAM --> TeamRepo : true/false
                deactivate TEAM
        end

        TeamRepo --> CTRL : team
        deactivate TeamRepo

    CTRL -> PLAT: getAgenda()
    activate PLAT

    PLAT --> CTRL: agenda
    deactivate PLAT

    CTRL -> AGENDA: getTaskListByTeam(team)
    activate AGENDA


    AGENDA -> TASKSAGENDA: getTaskListByTeam(team)

    activate TASKSAGENDA
        loop for each task in TaskAgenda

                TASKSAGENDA -> TASKAGENDA: hasTaskByTeam(team)

                activate TASKAGENDA

                TASKAGENDA --> TASKSAGENDA: true/false
                deactivate TASKAGENDA

                alt hasTaskByTeam == true
                    TASKSAGENDA -> TASKSAGENDA : addTaskListTeam()
                    activate TASKSAGENDA

                    TASKSAGENDA --> TASKSAGENDA : true/false
                    deactivate TASKSAGENDA
                end

        end

    TASKSAGENDA --> AGENDA : taskListTeam

    deactivate TASKSAGENDA


    AGENDA --> CTRL: taskListTeam
    deactivate AGENDA

        CTRL -> AGENDA: filterTasksByStatusDate(taskListTeam, status, startDate, endDate)
        activate AGENDA

        AGENDA -> TASKSAGENDA : filterTasksByStatusDate(taskListTeam, status, startDate, endDate)
        activate TASKSAGENDA



                loop for each taskAgenda in taskListTeam
        TASKSAGENDA -> TASKAGENDA : hasStatus(status)
        activate TASKAGENDA

        TASKAGENDA -> TASKToDOList : hasStatus(status)

        activate TASKToDOList

        TASKToDOList --> TASKAGENDA : true/false

        deactivate TASKToDOList

        TASKAGENDA --> TASKSAGENDA : true/false
        deactivate TASKAGENDA

        TASKSAGENDA -> TASKAGENDA : isBetweenDates(startDate, endDate)
        activate TASKAGENDA

        TASKAGENDA --> TASKSAGENDA : true/false
        deactivate TASKAGENDA

            alt hasStatus == true && isBetweenDates == true
                TASKSAGENDA -> TASKSAGENDA: addFilteredTaskListTeam()
                activate TASKSAGENDA

                TASKSAGENDA --> TASKSAGENDA: true/false
                deactivate TASKSAGENDA
            end

    end

        TASKSAGENDA --> AGENDA : filteredTaskListTeam
        deactivate TASKSAGENDA

        AGENDA --> CTRL: filteredTaskListTeam
        deactivate AGENDA

        CTRL -> AGENDA: sortTaskAgendaByDate(filteredTaskListTeam)
        activate AGENDA

        AGENDA -> TASKSAGENDA: sortTaskAgendaByDate(filteredTaskListTeam)
        activate TASKSAGENDA

        TASKSAGENDA --> AGENDA: sortedTaskListTeam
        deactivate TASKSAGENDA

        AGENDA --> CTRL: sortedTaskListTeam
        deactivate AGENDA
CTRL -> TASKAGENDAMAPPER : toDTO(listTaskAgenda)

activate TASKAGENDAMAPPER

ref over TASKAGENDAMAPPER

Desing in 23

end
TASKAGENDAMAPPER --> CTRL : listTaskAgendaDTO

deactivate TASKAGENDAMAPPER
        CTRL --> UI : sortedTaskListTeam

        deactivate CTRL

    UI --> Col : shows list of assigned tasks
    deactivate UI

@enduml