@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype orto

skinparam classAttributeIconSize "1"

package "UI" <<Folder>> {
    class ConsultAssignedTasksListUI {
    }
}


package "Controller" <<Folder>> {

    class ConsultAssignedTasksController {
        + getTasksBetweenTwoDates(startDate, endDate, status)
        - getCollaboratorFromSession()
    }

}

'left to right direction
package "Domain" <<Folder>> {

    package "Domain.Application" <<Folder>> {

        class ApplicationSession
        {
            + static getInstance()
            + getCurrentSession()
        }

        class UserSession
        {
            + getUserEmail()
        }
    }

    package "Domain.Model" <<Folder>> {

        interface GreenSpace {
            + getName()
            + getArea()
            + getAddress()
        }

        class Team{
            + hasTeamByCollaborator(collaborator)

        }

        class Garden implements GreenSpace{

        }

        class MediumPark implements GreenSpace{

        }

        class LargePark implements GreenSpace{

        }

        interface ICollaborator{
            + getEmail()
            + hasEmail(email)

        }

        class Task {
            - String taskDescription

            + Task(taskDescription)
        }

        class TasksAgenda {

            + filterTasksByStatusDate(taskListTeam, status, startDate, endDate)
            + sortTaskAgendaByDate(filteredTaskListTeam)
            - addTaskListTeam()
            - addFilteredTaskListTeam()
        }

        class TaskAgenda {
            - String urgency
            - int expectedDuration
            - String status
            - Date startDate
            - Date endDate

            - hasTaskByTeam(team)
            - hasStatus(status)
            - isBetweenDates(startDate, endDate)
        }

        class Collaborator implements ICollaborator{
            - String name
            - Date dateOfBirth
            - Date admissionDate
            - String email
            - int taxpayer

            + isEquals(collaborator)
        }

        class Agenda{

            + Agenda()
            + getTaskListByTeam(team)
            + filterTasksByStatusDate(taskListTeam, status, startDate, endDate)
            + sortTaskAgendaByDate(filteredTaskListTeam)
        }

    }

    package "Domain.Repository" <<Folder>> {

        class Repositories {

            - Repositories()
            + getInstance() : Repositories
            + getCollaboratorRepository()
            + getTeamRepository();
            + getAgenda()
        }

        class CollaboratorRepository {

            + getCollaboratorByEmail(email)
        }

        class TeamRepository {

            + getTeamByCollaborator(collaborator)
        }
    }
}

'-------------------Instance-------------------
Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

'-------------------UI-------------------
ConsultAssignedTasksListUI ..> ConsultAssignedTasksController

'-------------------Controller-------------------
ConsultAssignedTasksController ...> Repositories : repositories
ConsultAssignedTasksController ...> ApplicationSession
ConsultAssignedTasksController ...> UserSession
ConsultAssignedTasksController ...> CollaboratorRepository
ConsultAssignedTasksController ...> TeamRepository
ConsultAssignedTasksController ...> ICollaborator
ConsultAssignedTasksController ...> GreenSpace
ConsultAssignedTasksController ...> Task
ConsultAssignedTasksController ...> TaskAgenda
ConsultAssignedTasksController ...> Agenda
ConsultAssignedTasksController ...> Team

'-------------------ApplicationSession-------------------
ApplicationSession --> "1" UserSession : userSession

'-------------------Repositories-------------------
Repositories ---> "1" CollaboratorRepository : CollaboratorRepository
Repositories -> "1" Agenda : Agenda
Repositories --> "1" TeamRepository : TeamRepository

'-------------------CollaboratorRepository-------------------
CollaboratorRepository "1"  --> "*" ICollaborator : collaboratorList

'-------------------TeamRepository-------------------
TeamRepository "1" -> "*" Team : teamList

'-------------------Agenda-------------------
Agenda "1" --> "1" TasksAgenda : tasksAgenda

TasksAgenda "1" -> "*" TaskAgenda: taskAgendaList

'-------------------TaskAgenda-------------------
TaskAgenda "*" --> "1" GreenSpace : greenSpace
TaskAgenda "1..*" -> "1" Task : task
TaskAgenda "*" ---> "1" Team : team

'-------------------Team-------------------
Team "1" --> "1..*" Collaborator : collaboratorList

@enduml

