@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model


class Collaborator {
    name
    dateOfBirth
    admissionDate
    address
    phoneNumber
    email
    cc
    cardNumber

}
class VehicleFleetManager {
}

class HumanResourceManager {
}

class GreenSpaceManager{
}

class GreenSpaceUser{
}

class Team{
}

class Agenda{
}

class Task{
}

class Vehicle{
    brand
    model
    type
    tare
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    checkupFrequency
    licensePlate
}

class CheckUp{
    date
    km
}

class Skill{
    name
}

class Job{
    name
}

class Park{
}

class GreenSpace{
}

class Garden{
}

class TypePark{}


GreenSpace <|- Park
GreenSpace <|-- Garden
Park "1..*" -- "1" TypePark : has >
Park "0..1" -- "1..*" Garden : contain >



Collaborator  <|--  HumanResourceManager
Collaborator <|- VehicleFleetManager
Collaborator <|--- GreenSpaceManager
Collaborator <|-- GreenSpaceUser

HumanResourceManager "1" --- "1..*" Collaborator : registers >
HumanResourceManager "1" - "1..*" Job : registers >
HumanResourceManager "1" -- "1..*" Skill : registers >
HumanResourceManager "1" -- "1..*" Team : generate >


Collaborator "0..1" -- "*" Vehicle : drives/use >
Collaborator "1..*" ---- "1" Team : Contains <

Team "1" -- "1" Agenda : carries out >

Agenda "1" -- "*" Task : consists of >

Vehicle "1" -- "*" CheckUp :  does >

Skill "1..*" -- "*" Collaborator : has <

Job "1" -- "1..*" Collaborator : has <

VehicleFleetManager "1" -- "1..*" Vehicle : registers/managing >
VehicleFleetManager "1" -- "1..*" CheckUp : registers >

GreenSpaceManager "1..*" -- "*" GreenSpace :  managing >
GreenSpaceUser "*" -- "1..*" GreenSpace :  use >

@enduml