@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "greenSpaceRepository\n:GreenSpaceRepository" as GSR
participant "greenSpace\n:GreenSpace" as GREENSPACE
participant "address\n:Address" as ADDRESS
participant "postCode\n:PostCode" as PSTCODE

autonumber 15

--> GSR :  registerGreenSpace(name,area,streetName, postCodeNumber,localization)

autonumber 15.1

activate GSR

group Register GreenSpace

GSR -> GREENSPACE** : create(name,area,streetName, postCodeNumber,localization)
activate GREENSPACE

GREENSPACE -> ADDRESS**  : create(streetName,postCodeNumber,localization)

activate ADDRESS

ADDRESS -> PSTCODE** : create(postCodeNumber,localization)

activate PSTCODE

PSTCODE -> PSTCODE : validation()

activate PSTCODE

PSTCODE --> PSTCODE : true/false

deactivate PSTCODE

PSTCODE --> ADDRESS : postCode

deactivate PSTCODE

ADDRESS -> ADDRESS : validation()

activate ADDRESS
ADDRESS --> ADDRESS : true/false

deactivate ADDRESS

ADDRESS --> GREENSPACE : Address
deactivate ADDRESS

GREENSPACE -> GREENSPACE : validationGreenSpace()

activate GREENSPACE

GREENSPACE --> GREENSPACE : true/false

deactivate GREENSPACE

GREENSPACE -->  GSR : greenSpace
deactivate GREENSPACE

GSR-> GSR : addGreenSpace(greenSpace)

activate GSR

GSR -> GSR :  validationAllData(greenSpace)

activate GSR

GSR --> GSR : true/false
deactivate GSR

GSR --> GSR : true/false
deactivate GSR

end

autonumber 16

<--GSR : greenSpaceManager

deactivate GSR

@enduml