@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US27 - List all Green Spaces

autonumber

actor "Green Space Manager (GSM)" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to list all associated green spaces
    activate System

        System --> GSM : shows list of green spaces
    deactivate System

@enduml