@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SD) - US27 - List Green Spaces

autonumber

'hide footbox
actor "Green Spaces Manager (GSM)" as GSM
participant ":ListGreenSpacesUI" as UI
participant ":ListGreenSpacesController" as CTRL
participant "manager\n:GreenSpaceManager" as GSMO
participant "greenSpaces\n:GreenSpaces" as GSL
participant "sortAlg\n:Sortable" as SA
participant "greenSpaceMapper\n:GreenSpaceMapper" as GSMP

activate GSM

        GSM -> UI : asks to list all associated green spaces
    activate UI

        UI -> CTRL : getGreenSpaceManagerGSpaceSorted()
    activate CTRL

        CTRL -> CTRL : getGSMFromSession()
    activate CTRL

        ref over CTRL
            Design in US20
        end ref

        CTRL --> CTRL : manager
    deactivate CTRL

        CTRL -> GSMO : getGreenSpaces()
    activate GSMO

        GSMO -> GSL : getSortedGreenspaces()
    activate GSL

        GSL -> SA : getSortedList(greenSpaceList)
    activate SA

        SA --> GSL : greenSpaceListSorted
    deactivate SA

        GSL --> GSMO : greenSpaceListSorted
    deactivate GSL

        GSMO --> CTRL : greenSpaceListSorted
    deactivate GSMO

        CTRL -> GSMP : toDTOGreenSpace(greenSpaceListSorted)
    activate GSMP

        ref over GSMP
            Design in US21
        end ref

       GSMP --> CTRL : greenSpaceListDto
    deactivate GSMP

        CTRL --> UI : greenSpaceListDto
    deactivate CTRL

        UI --> GSM : shows list of green spaces
    deactivate UI

deactivate GSM
@enduml