@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'hide footbox
participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobRepository:\njobRepository" as JobRepository

autonumber 11
-> CTRL : getJobByName(jobName)
activate CTRL

autonumber 11.1
    group Get Job Object

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton -> CTRL : repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getJobRepository()
        activate PLAT

        PLAT -> CTRL : jobRepository
        deactivate PLAT

        CTRL -> JobRepository : getJobByName(jobName)
        activate JobRepository

        JobRepository --> CTRL : job
        deactivate JobRepository
    end
    autonumber 12
   <-- CTRL : job
deactivate CTRL

@enduml