@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model - US21 Add new entry to the To-Do-List

class Collaborator {
    name
    dateOfBirth
    admissionDate
    phoneNumber
    taxpayer
    email
}

class Document{
    docType
    number
}

class Address {
    streetName
    postCode
    doorNumber
}

class GreenSpaceManager {
}

class ToDoList {
}

class Task {
    description
    urgency
    duration
    status
}

Collaborator "1" - "1" Document : has >
Collaborator "1..*" -- "1" Address : lives >
Collaborator  <|--  GreenSpaceManager

GreenSpaceManager "1..*" -- "1" Task : creates >
GreenSpaceManager "1..*" - "1" ToDoList : inserts new entry >

Task "*" -- "1" ToDoList : includes <

@enduml