@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model - US21 Add new entry to the To-Do-List

class Collaborator {
    name
    dateOfBirth
    admissionDate
    phoneNumber
    taxpayer
    email
}

class Address {
    street
    doorNumber
}

class PostCode{
    postCodeNumber
    localization
}

class GreenSpaceManager {
}

class ToDoList {
}

class Task {
    description
}

class TaskToDoList{
    status
    urgency
    duration
}

class GreenSpace {
    name
    area
}

class Garden {
}

class MediumPark {
}

class LargePark {
}

Collaborator  <|--  GreenSpaceManager

GreenSpaceManager "1..*" -- "1..*" Task : creates >
GreenSpaceManager "1..*" - "1..*" TaskToDoList : inserts new entry >
GreenSpaceManager "1" - "*" GreenSpace : register/manages >

GreenSpace <|-- Garden
GreenSpace <|-- MediumPark
GreenSpace <|-- LargePark
GreenSpace "1" - "1" Address : is located in >

Address "1..*" -- "1" PostCode : has >

Task "*" -- "1" ToDoList : includes <
Task "1" -- "*" TaskToDoList : contains <
(Task,ToDoList) .. TaskToDoList

TaskToDoList "1..*" --- "1" GreenSpace :  Carried out in  >

ToDoList "1" --- "1..*" TaskToDoList : includes >

@enduml