@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register a collaborator

autonumber

actor "Human Resource Manager (HRM)" as HRM
participant ":System" as System

activate HRM

    HRM -> System : asks to register a new collaborator
    activate System

    System --> HRM : shows job list and asks to type one
    deactivate System

    HRM -> System :  types a job
    activate System

    System --> HRM : requests data (name, birthdate, admission date, address(streetName, postCode, doorNumber), \nmobile, email, taxpayer number,ID doc type and respective number)
    deactivate System

    HRM -> System : types requested data
    activate System

    System --> HRM : shows all data and requests confirmation
    deactivate System

    HRM -> System : confirms data
    activate System

    System --> HRM : displays operation success
    deactivate System

@enduml