@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model - US27 List all Green Spaces

class Collaborator {
    name
    dateOfBirth
    admissionDate
    phoneNumber
    taxpayer
    email
}

class Document{
    docType
    number
}

class Address {
    streetName
    postCode
    doorNumber
}

class GreenSpaceManager {
}

class GreenSpace{
    name
    area
}

class SortingAlgorithm {
}

Collaborator "1" - "1" Document : has >
Collaborator "1..*" -- "1" Address : lives >
Collaborator  <|--  GreenSpaceManager

GreenSpaceManager "1" - "1..*" GreenSpace : manages >

GreenSpace "1" - "1" Address : is located in >
GreenSpace "1" -- "1" SortingAlgorithm : makes use of >

@enduml