@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Collaborator {
    name
    dateOfBirth
    admissionDate
    phoneNumber
    taxpayerNumber
    email
}

class Document{
    number
}

class DocumentType{
    type
}

class Address {
    street
    doorNumber
}

class PostCode{
    postCodeNumber
    localization
}

class VehicleFleetManager {
}

class HumanResourceManager {
}

class Brand {
     name
}

class Model {
     name
     type
     tare
     grossWeight
     checkupFrequencyKm
}

class Vehicle {
    currentKm
    registerDate
    acquisitionDate
    licensePlate
}

class Skill{
    name
}

class Job{
    name
}
class Team{
}

class CheckUp{
    date
    km
}

class GreenSpaceManager {
}

class GreenSpace {
    name
    area
}

class Garden {
}

class MediumPark {
}

class LargePark {
}

class ToDoList {
}

class TaskToDoList{
    status
    urgency
    duration
}

class TaskAgenda{
    startDate
    endDate
}

class Task {
    description
}

class Agenda{
}

Address "1..*" -- "1" PostCode : has >

Document "1..*" - "1" DocumentType : has >

'-------------Collaborator-------------
Collaborator "1" - "1" Document : has >
Collaborator "1..*" --- "1" Job : has >
Collaborator  <|--  HumanResourceManager
Collaborator <|-- VehicleFleetManager
GreenSpaceManager  -|>  Collaborator
Address "1" - "1..*" Collaborator : lives <
Skill "*" ---------- "*" Collaborator : has <
Collaborator "1..*" ----- "1" Team : Contains <

'-------------HumanResourceManager-------------
HumanResourceManager "1" -- "1..*" Skill : registers >
HumanResourceManager "1" -- "1..*" Job : registers >
HumanResourceManager "1" --- "1..*" Collaborator : Registers >
HumanResourceManager "1" -- "1..*" Team : defines >

'-------------VehicleFleetManager-------------
VehicleFleetManager "1" -- "1..*" Vehicle : registers/manages >
VehicleFleetManager "1" -- "1..*" CheckUp : Registers >

'-------------Brand-------------
Brand "1" -  "1..*" Model : has >

'-------------Vehicle-------------
Vehicle "1..*" -- "1" Model : has >
Vehicle "1" -- "*" CheckUp : does >

'-------------GreenSpaceManager-------------
GreenSpaceManager "1" - "*" GreenSpace : register/manages >
GreenSpaceManager "1..*" -- "1..*" Task : creates >
GreenSpaceManager "1..*" - "1..*" TaskToDoList : inserts new entry >
GreenSpaceManager "1..*" - "1..*" TaskAgenda : inserts new entry >
GreenSpaceManager "1..*" - "1" TaskAgenda : Assign Team to an entry >

'-------------GreenSpace-------------
GreenSpace "1" - "1" Address : is located in >
GreenSpace <|-- Garden
GreenSpace <|-- MediumPark
GreenSpace <|-- LargePark
GreenSpace "*" -- "1" SortingAlgorithm : makes use of >

'-------------Task-------------
TaskAgenda "1..*" --- "1" GreenSpace :  Carried out in  >
TaskToDoList "1..*" --- "1" GreenSpace :  Carried out in  >

Task "*" -- "1" ToDoList : includes <

Team "1" --- "*" TaskAgenda : executes by <
Agenda "1" - "*" Task : contains >

EmailService "1" -- "*" Team :  send email to all elements of >


(Task,ToDoList) .. TaskToDoList
(Task,Agenda) .. TaskAgenda

TaskAgenda - TaskToDoList : includes >
@enduml
