@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Collaborator {
    name
    dateOfBirth
    admissionDate
    phoneNumber
    taxpayerNumber
    email
}

class Document{
    number
}

class DocumentType{
    type
}

class Address {
    street
    doorNumber
}

class PostCode{
    postCodeNumber
    localization
}

class VehicleFleetManager {
}

class HumanResourceManager {
}

class GreenSpaceManager{
}

class GreenSpaceUser{
}

class QualityAssessmentManager{}

class Team{
    id
}

class Agenda{}

class ToDoList{}

class Task {
    description
}

class Brand {
     name
}

class Model {
     name
     type
     tare
     grossWeight
     checkupFrequencyKm
}

class Vehicle {
    currentKm
    registerDate
    acquisitionDate
    licensePlate
}

class CheckUp{
    date
    km
}

class Skill{
    name
}

class Job{
    name
}

class MediumPark{
}

class GreenSpace{
    name
    area
}

class Garden{}

class LargePark{}

class PlantMaterial{
    name
}

class Tree{}

class UrbanFurniture{
    name
}

class Bench{}

class InfraStructure{
    name
}

class IrrigationSystem{}

class Pipe{
    distance
}

class WaterPoint{
    designation
}

class Service{
    name
}

class Machine{
    type
}

class Equipment{
    name
}

class EmailService{
}

class TaskToDoList{
    taskReference
    status
    urgency
    aproxExpectedDuration
}

class TaskAgenda{
    startDate
    expectedDuration
}

class Sortable{
}

class UserPortal{
}

class Comment{
    message
}

'-------------Address-------------
Address "1..*" - "1" PostCode : has >

'-------------Agenda-------------
Agenda "1" -u- "*" TaskAgenda : contains >

'-------------Brand-------------
Brand "1" -l  "1..*" Model : has >

'-------------Collaborator-------------
Collaborator <|-u  QualityAssessmentManager
Collaborator <|-l GreenSpaceManager
Collaborator <|-  HumanResourceManager
Collaborator <|-d VehicleFleetManager
Collaborator "1..*" - "1" Address : lives >
Collaborator "*" -- "*" Vehicle : drives/uses >
Collaborator "1..*" --- "1" Team : Contains <
Collaborator "1" -l "1" Document : has
Collaborator "1..*" --- "1" Job : has >
Collaborator "1..*" - "*" Skill : has >

'-------------Document-------------
Document "1..*" - "1" DocumentType : has >

'-------------Garden-------------
Garden "1" ---- "0..1" IrrigationSystem : has >
Garden "1..*" -- "*" Tree : possess >
Garden "1..*" --- "*" Bench : possess >

'-------------GreenSpace-------------
GreenSpace <|-- MediumPark
GreenSpace <|-- Garden
GreenSpace <|-- LargePark
GreenSpace "1" - "1" Address : is located in >
GreenSpace "*" -- "1" Sortable : makes use of >

'-------------GreenSpaceManager-------------
GreenSpaceManager "1..*" -- "*" GreenSpace :  registers/manages >
GreenSpaceManager "1..*" -- "1..*" Task : creates >
GreenSpaceManager "1..*" - "1..*" TaskToDoList : inserts >
GreenSpaceManager "1..*" - "1..*" TaskAgenda : inserts new entry >
GreenSpaceManager "1..*" - "1" TaskAgenda : Assign Team >
(GreenSpaceManager,TaskAgenda) .. Team
(GreenSpaceManager,TaskAgenda) .. Vehicle

'-------------GreenSpaceUser-------------
GreenSpaceUser "*" -- "1..*" GreenSpace :  uses >
GreenSpaceUser "1..*" -u "*" Comment :  sends >
GreenSpaceUser "1..*" - "1" UserPortal : uses >
(GreenSpaceUser,GreenSpace) .. Comment

'-------------HumanResourceManager-------------
HumanResourceManager "1" -- "1..*" Collaborator : registers >
HumanResourceManager "1" - "1..*" Job : registers >
HumanResourceManager "1" -- "1..*" Skill : registers >
HumanResourceManager "1" -- "1..*" Team : defines >

'-------------InfraStructure-------------
InfraStructure <|- IrrigationSystem

'-------------IrrigationSystem-------------
IrrigationSystem "1" -- "1..*" Pipe : contains >

'-------------LargePark-------------
LargePark "1..*" --- "1..*" InfraStructure : includes >
LargePark "1..*" -- "*" Service : includes >
LargePark "0..1" - "1..*" Garden : contains >

'-------------MediumPark-------------
MediumPark "1..*" -- "*" InfraStructure : includes >
MediumPark "0..1" -- "1..*" Garden : contains >

'-------------Pipe-------------
Pipe "1..*" -- "2" WaterPoint : contains >

'-------------PlantMaterial-------------
PlantMaterial <|- Tree

'-------------Task-------------
Task "*" --- "1" ToDoList : includes <
Task "1..*" - "1..*" GreenSpace :  Carried out in  >
(Task,ToDoList) .. TaskToDoList

'-------------TaskAgenda-------------
TaskAgenda "1..*" --- "1" GreenSpace :  Carried out in  >
TaskAgenda "1" -- "1..*" Equipment : Carried out with >
TaskAgenda "1" - "1" TaskToDoList : includes >

'-------------TaskToDoList-------------
TaskToDoList "1..*" ----- "1" GreenSpace :  Carried out in  >
TaskToDoList "1" -u- "1" Task : contains >

'-------------Team-------------
Team "1" --- "*" TaskAgenda : executed by <
Team "*" -u- "1" EmailService : makes use of >

'-------------ToDoList-------------
ToDoList "1" -- "*" TaskToDoList : includes  >

'-------------UrbanFurniture-------------
UrbanFurniture <|- Bench

'-------------UserPortal-------------
UserPortal "1" -u- "*" Comment : has

'-------------Vehicle-------------
Vehicle "1..*" --- "1..*" Task :  needed to carry out >
Vehicle "1..*" -- "1..*" Machine :  transports >
Vehicle "1..*" - "1..*" Equipment :  transports >
Vehicle "1..*" --- "1" Model : has >
Vehicle "1" -- "*" CheckUp : does >

'-------------VehicleFleetManager-------------
VehicleFleetManager "1" - "1..*" Machine :  manages >
VehicleFleetManager "1" - "1..*" Equipment :  manages >
VehicleFleetManager "1" -- "1..*" Vehicle : registers/manages >
VehicleFleetManager "1" -- "1..*" CheckUp : Registers >

@enduml