@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


participant "collaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository
participant "collaborator:\nCollaborator" as Collaborator
participant "document:\nDocument" as Doc

autonumber 19
-> CollaboratorRepository : registerCollaborator(name, birthdate, \nadmission date, address, mobile, \nemail, ID doc type, respective number, job)


autonumber 19.1
activate CollaboratorRepository

CollaboratorRepository -> CollaboratorRepository : registerDocument(docType, number)
activate CollaboratorRepository


    group Create Collaborator
    CollaboratorRepository -> Doc** : create(docType, number)
    activate Doc

    Doc -> Doc : validate(docType, number)

    Doc -> CollaboratorRepository : document
    deactivate Doc

    CollaboratorRepository -> CollaboratorRepository : document
    deactivate CollaboratorRepository


CollaboratorRepository -> Collaborator**: create(name, birthdate, \nadmission date, address, mobile, \nemail, document, job)

            activate Collaborator

                Collaborator -> Collaborator: validateCollaborator(collaborator)
                Collaborator --> CollaboratorRepository : collaborator

            deactivate Collaborator

        CollaboratorRepository -> CollaboratorRepository: addCollaborator(collaborator)

        activate CollaboratorRepository
            CollaboratorRepository -> CollaboratorRepository: validateCollaborator(collaborator)
            activate CollaboratorRepository

                CollaboratorRepository --> CollaboratorRepository : true/false
            deactivate CollaboratorRepository

            CollaboratorRepository --> CollaboratorRepository : true/false

        deactivate CollaboratorRepository
    end group

    autonumber 20
<-- CollaboratorRepository : collaborator

@enduml