@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobRepository:\njobRepository" as JobRepository

autonumber 2
-> CTRL: getJobList()

autonumber 2.1
activate CTRL
    group Get Job List

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton -> CTRL : repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getJobRepository()
        activate PLAT

        PLAT -> CTRL : jobRepository
        deactivate PLAT

        CTRL -> JobRepository : getJobList
        activate JobRepository

        JobRepository --> CTRL : jobList
        deactivate JobRepository
    end

    autonumber 3
    <-- CTRL : jobList
deactivate CTRL


@enduml