@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resource Manager (HRM)" as HRM
participant ":RegisterColllaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository

activate HRM

    HRM -> UI : asks to register a new collaborator
    activate UI

        UI -> CTRL : getJobList()
        activate CTRL

            ref over CTRL
                Get Job List

            end ref
        CTRL --> UI : jobList
        deactivate CTRL

        UI --> HRM : shows jobs list and asks to select one
        deactivate UI

        HRM -> UI :  types a job
        activate UI

        UI --> HRM : requests data (name, birthdate, admission date, address, \nmobile, email, ID doc type and respective number)
        deactivate UI

        HRM -> UI : types requested data
        activate UI

        UI --> HRM : shows data and requests confirmation
        deactivate UI

        HRM -> UI : confirms data
        activate UI

        UI -> CTRL : registerCollaborator(name, birthdate, \nadmission date, address, mobile, \nemail, ID doc type, respective number, \njob name)
        activate CTRL


            CTRL -> CTRL : getJobByName(jobName)
            activate CTRL

                ref over CTRL
                    Get Job Object
                end ref
                CTRL --> CTRL : job
            deactivate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getCollaboratorRepository()
                activate PLAT

                    PLAT -> CTRL : collaboratorRepository
                deactivate PLAT

                CTRL -> CollaboratorRepository : registerCollaborator(name, birthdate, \nadmission date, address, mobile, \nemail, ID doc type, respective number, job)
                activate CollaboratorRepository

                ref over CollaboratorRepository
                    Create Collaborator
                end ref

                CollaboratorRepository --> CTRL : collaborator
                deactivate CollaboratorRepository

                CTRL --> UI : collaborator
                deactivate CTRL

                UI --> HRM : displays operation success
                deactivate UI

@enduml