@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model



class VehicleFleetManager {

}

class Collaborator {
    name
    dateOfBirth
    admissionDate
    phoneNumber
    email
}

class Document{
    docType
    number
}

class Address {
    streetName
    postCode
    doorNumber
}


class Vehicle{
    brand
    model
    type
    tare
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    checkupFrequency
    licensePlate
}
class Brand{
    name
}

class Model{
    name
}

class CheckUp{
    date
    km
}



Collaborator "1" - "1" Document : has >

Collaborator "1..*" -- "1" Address : lives >
Collaborator <|- VehicleFleetManager

Vehicle "1" -- "*" CheckUp :  does >
VehicleFleetManager "1" -- "1..*" Vehicle : Registers >
Vehicle "1..*" -- "1" Brand : has >
Brand "1" -- "1..*" Model : has >

Vehicle "1..*" -- "1" Model :  has >

@enduml