@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignTeamAgendaController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agenda\n:Agenda" as AGENDA
participant "listTaskAgenda\n:List<AgendaTask>" as LSTASK
participant "agendaTask\n:AgendaTask" as TASK
participant "greenSpace\n:GreenSpace" as GREENSPACE

autonumber 11

--> CTRL : getAllTaskByGreenSpace(greenSpaceList)

autonumber 11.1

activate CTRL

group Get All Task By GreenSpace

CTRL -> RepositorySingleton : getInstance()

activate RepositorySingleton

RepositorySingleton --> CTRL : repositories

deactivate RepositorySingleton

CTRL -> PLAT : getAgenda()

activate PLAT

PLAT --> CTRL: agenda

deactivate PLAT

CTRL -> AGENDA : getAllTaskByGreenSpace(greenSpaceList)


activate AGENDA

AGENDA -> LSTASK** : create

loop for each Task in listTask[in Agenda]

AGENDA -> TASK : verifyGreenSpace(greenSpaceList)

activate TASK

TASK -> TASK : verifyNullTeam()

activate TASK

TASK --> TASK : true/false

deactivate TASK

alt verifyNullTeam == true

loop for each GreenSpace in ListGreenSpace

TASK -> GREENSPACE : equalsGreenSpace(greenSpace)

activate GREENSPACE

GREENSPACE --> TASK : true/false

deactivate GREENSPACE

end

end
TASK -> AGENDA : taskAgenda

deactivate TASK

alt verifyGreenSpace != null

AGENDA -> LSTASK : add(taskAgenda)

activate LSTASK

LSTASK --> AGENDA : true/false

deactivate LSTASK

end

end

AGENDA --> CTRL : listTaskAgenda

deactivate AGENDA

end

autonumber 12

<--CTRL : listTaskAgenda

deactivate CTRL
@enduml