@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignTeamAgendaController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agenda\n:Agenda" as AGENDA
participant "agendaTask\n:AgendaTask" as TASK
participant "greenSpace\n:GreenSpace" as GREENSPACE

autonumber 11

--> CTRL : getAllTaskByGreenSpace(listGreenSpace)

autonumber 11.1

activate CTRL

group Get All Task By GreenSpace

CTRL -> RepositorySingleton : getInstance()

activate RepositorySingleton

RepositorySingleton --> CTRL : repositories

deactivate RepositorySingleton

CTRL -> PLAT : getAgenda()

activate PLAT

PLAT --> CTRL: agenda

deactivate PLAT

CTRL -> AGENDA : getAllTaskByGreenSpace(listGreenSpace)

activate AGENDA

loop for each Task in listTask[in Agenda]

AGENDA -> TASK : verifyGreenSpace(listGreenSpace)

activate TASK

TASK -> TASK : verifyNullTeam()

activate TASK

TASK --> TASK : true/false

deactivate TASK

alt verifyNullTeam == true

loop for each GreenSpace in ListGreenSpace

TASK -> GREENSPACE : equalsGreenSpace(greenSpace)

activate GREENSPACE

GREENSPACE --> TASK : true/false

deactivate GREENSPACE

end
end
TASK -> AGENDA : true/false

deactivate TASK

alt verifyGreenSpace == true

AGENDA -> AGENDA : addListTaskByGreenSpace(task)

activate AGENDA

AGENDA --> AGENDA : true/false

deactivate AGENDA

end

end

AGENDA --> CTRL : listTask

deactivate AGENDA

end

autonumber 12

<--CTRL : listTask

deactivate CTRL
@enduml