@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignTeamAgendaController" as CTRL
participant "agenda\n:Agenda" as AGENDA

participant "agendaTask\n:AgendaTask" as TASK

autonumber 35

--> CTRL : assignTeamTask(teamCollaboratorName,taskParkName,taskName)

autonumber 35.1
group Assign Team Task

activate CTRL

CTRL -> AGENDA : assignTeamTask(team,task)

activate AGENDA

loop for each task in listTask[in Agenda]

AGENDA -> TASK : equalsTask(task)

activate TASK

TASK --> AGENDA : true/false

deactivate TASK

alt equalsTask == true

AGENDA -> TASK : updateTeam(team)

activate TASK

TASK --> AGENDA : true/false

deactivate TASK

end

end

AGENDA --> CTRL : true/false

deactivate AGENDA

end

autonumber 36

<--CTRL : true/false

deactivate CTRL
@enduml