@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":TeamMapper" as TEAMMP
participant "listTeam\n:List<Team>" as TEAMLIST
participant "listTeamDto\n:List<TeamDto>" as LSTEAMDTO
participant "objDto\n:TeamDto" as DTOTEAM

autonumber 25

--> TEAMMP : toDTO(listTeam)

autonumber 25.1

activate TEAMMP

group To DTO List

TEAMMP --> LSTEAMDTO** : create()

loop for each object in listTeam

TEAMMP -> TEAMLIST : get(i)

activate TEAMLIST

TEAMLIST --> TEAMMP : obj

deactivate TEAMLIST

TEAMMP -> TEAMMP : objDto = toDTO(obj)

activate TEAMMP

TEAMMP --> DTOTEAM** : create(obj)

deactivate TEAMMP

TEAMMP -> LSTEAMDTO : add(objDto)

activate LSTEAMDTO

LSTEAMDTO --> TEAMMP : true/false

deactivate LSTEAMDTO

end

end

autonumber 26

<-- TEAMMP : listTeamDto

deactivate TEAMMP
@enduml
