@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - US23 - Assign Team in Entries

autonumber

'hide footbox
actor "Green Space Manager (GSM)" as GSM

participant ":AssignTeamAgendaUI" as UI
participant ":AssignTeamAgendaController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "teamRepository\n:TeamRepository" as TR
participant "greenSpaceManager\n:GreenSpaceManager" as GSMO
participant "greenSpaces\nGreenSpaces" as GREENSPACES
participant "teamRepository\n:TeamRepository" as TEAMREPO
participant "agenda\n:Agenda" as AGENDA
participant "teamMapper\n:TeamMapper" as TEAMMAPPER
participant "taskAgendaMapper\n:TeamMapper" as TASKAGENDAMAPPER

activate GSM	

GSM	 -> UI : asks to assign Team to entry in the Agenda

activate UI

UI -> CTRL : getAllTaskByGSM()

activate CTRL

CTRL -> CTRL : getGSMFromSession()

activate CTRL

ref over CTRL

Get GreenSpaceManager

end

CTRL --> CTRL : greenSpaceManager

deactivate CTRL

CTRL -> CTRL : getAllGreenSpaceByGSM(greenSpaceManager)

activate CTRL

CTRL -> GSMO : getListGreenSpace()
activate GSMO

GSMO -> GREENSPACES : getGreenSpaceList()

activate GREENSPACES

GREENSPACES --> GSMO : greenSpaceList
deactivate GREENSPACES

GSMO --> CTRL : greenSpaceList

deactivate GSMO

CTRL --> CTRL : greenSpaceList

deactivate CTRL

CTRL -> CTRL : getAllTaskByGreenSpace(greenSpaceList)

activate CTRL

ref over CTRL

Get All Task By GreenSpace

end

CTRL --> CTRL : listTaskAgenda

deactivate CTRL

CTRL -> TASKAGENDAMAPPER : toDTO(listTaskAgenda)

activate TASKAGENDAMAPPER

ref over TASKAGENDAMAPPER

toDTO List Task Agenda

end
TASKAGENDAMAPPER --> CTRL : listTaskAgendaDTO

deactivate TASKAGENDAMAPPER


CTRL --> UI : listTaskAgendaDTO

deactivate CTRL

UI --> GSM	 : Show a task name and greenSpaceName Task Agenda List and ask to select one
deactivate UI

GSM	->UI: choose a task

activate UI

UI -> CTRL : getAllTeams()

activate CTRL

CTRL -> RepositorySingleton : getInstance()

activate RepositorySingleton

RepositorySingleton --> CTRL : repositories

deactivate RepositorySingleton

CTRL -> PLAT : getTeamRepository()

activate PLAT

PLAT --> CTRL: teamRepository

deactivate PLAT

CTRL -> TR : getAllTeams()

activate TR

TR --> CTRL : listTeam

deactivate TR

CTRL -> TEAMMAPPER: toDTO(listTeam)

activate TEAMMAPPER

ref over TEAMMAPPER
SD_toDTO_List
end

TEAMMAPPER --> CTRL : listTeamDto

deactivate TEAMMAPPER

CTRL --> UI : listTeamDto

deactivate CTRL

UI --> GSM	 : show the list of the id teams and ask to choose one of them

deactivate UI

GSM	 -> UI : type a team

activate UI

UI --> GSM : show all data and request confirmation

deactivate UI

GSM -> UI : confirms data

activate UI

UI -> CTRL: assignTeamTask(teamId,taskReference)

activate CTRL

CTRL -> RepositorySingleton : getInstance()

activate RepositorySingleton

RepositorySingleton --> CTRL : repositories

deactivate RepositorySingleton

CTRL -> PLAT : getTeamRepository()

activate PLAT

PLAT --> CTRL: teamRepository

deactivate PLAT

CTRL -> TEAMREPO : getTeamById(teamId)

activate TEAMREPO

ref over TEAMREPO

Get team By ID

end

TEAMREPO --> CTRL : team

deactivate TEAMREPO

CTRL -> PLAT : getAgenda()

activate PLAT

PLAT --> CTRL: agenda

deactivate PLAT

CTRL -> AGENDA : getTaskByReference(taskReference)

activate AGENDA

ref over AGENDA

Get Task By Reference

end

AGENDA --> CTRL : taskAgenda

deactivate AGENDA

CTRL -> CTRL : assignTeam(team,taskAgenda)

activate CTRL

ref over CTRL

Assign Team Task

end

CTRL --> CTRL : true/false

deactivate CTRL

alt assignTeam == true

CTRL -> CTRL : sendEmailTeam(team, msg)

activate CTRL

ref over CTRL

Send Email By Team

end

CTRL --> CTRL : true/false

deactivate CTRL

end

CTRL --> UI : true/false

deactivate CTRL

UI --> GSM	 : displays operation success

deactivate UI

deactivate GSM
@enduml