@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "teamRepository\n:TeamRepository" as TEAMREPO
participant "team\n:Team" as TEAM

autonumber 37

--> TEAMREPO : getTeamById(teamId)

autonumber 37.1

activate TEAMREPO

group Get team By Id

loop for each team in teamList[in TeamRepository]

TEAMREPO -> TEAM : verifyIdTeam(teamId)

activate TEAM

TEAM --> TEAMREPO : true/false

deactivate TEAM

end

end

autonumber 38

<--TEAMREPO : team

deactivate TEAMREPO
@enduml