@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) - US23 - Assign Team in Entries

autonumber

'hide footbox
actor "Green Space Manager (GSM)" as GSM

participant ":AssignTeamAgendaUI" as UI
participant ":AssignTeamAgendaController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "teamRepository\n:TeamRepository" as TR
participant "greenSpaceManager\n:GreenSpaceManager" as GSMO
participant "greenSpaces\nGreenSpaces" as GREENSPACES
participant "teamRepository\n:TeamRepository" as TEAMREPO
participant "agenda\n:Agenda" as AGENDA

activate GSM	

GSM	 -> UI : asks to assign Team to entry in the Agenda

activate UI

UI -> CTRL : getAllTaskByGSM()

activate CTRL

CTRL -> CTRL : getGSMFromSession()

activate CTRL

ref over CTRL

Get GreenSpaceManager

end

CTRL --> CTRL : greenSpaceManager

deactivate CTRL

CTRL -> CTRL : getAllGreenSpaceByGSM(greenSpaceManager)

activate CTRL

CTRL -> GSMO : getListGreenSpace()
activate GSMO

GSMO -> GREENSPACES : getSortedGreenSpaces()

activate GREENSPACES

ref over GREENSPACES
Design in US27
end ref

GREENSPACES --> GSMO : greenSpaceList
deactivate GREENSPACES

GSMO --> CTRL : List greenSpace

deactivate GSMO

CTRL --> CTRL : List greenSpace

deactivate CTRL

CTRL -> CTRL : getAllTaskByGreenSpace(listGreenSpace)

activate CTRL

ref over CTRL

Get All Task By GreenSpace

end

CTRL --> CTRL : listTask

deactivate

CTRL --> UI : listTask

deactivate CTRL

UI --> GSM	 : Show Task List and ask to select one
deactivate UI

GSM	->UI: choose a task

activate UI

UI -> CTRL : getAllTeams()

activate CTRL

CTRL -> RepositorySingleton : getInstance()

activate RepositorySingleton

RepositorySingleton --> CTRL : repositories

deactivate RepositorySingleton

CTRL -> PLAT : getTeamRepository()

activate PLAT

PLAT --> CTRL: teamRepository

deactivate PLAT

CTRL -> TR : getAllTeams()

activate TR

TR --> CTRL : listTeam

deactivate TR

'CTRL -> TEAMMP : toDTO(listTeam)

'activate TEAMMP

'ref over TEAMMP
'    SD_toDTO_List
'end

'TEAMMP --> CTRL : listTeamDto


CTRL --> UI : listTeam

deactivate CTRL

UI --> GSM	 : show the list of the teams and ask to choose one of them

deactivate UI

GSM	 -> UI : type a team

activate UI

UI --> GSM : show all data and request confirmation

deactivate UI

GSM -> UI : confirms data

activate UI

UI -> CTRL: assignTeamTask(teamCollaboratorName,taskParkName,taskName)

activate CTRL

CTRL -> RepositorySingleton : getInstance()

activate RepositorySingleton

RepositorySingleton --> CTRL : repositories

deactivate RepositorySingleton

CTRL -> PLAT : getTeamRepository()

activate PLAT

PLAT --> CTRL: teamRepository

deactivate PLAT

CTRL -> TEAMREPO : getTeamByCollaboratorName(teamCollaboratorName)

activate TEAMREPO

ref over TEAMREPO

Get team By Collaborator

end

TEAMREPO --> CTRL : team

deactivate TEAMREPO

CTRL -> PLAT : getAgenda()

activate PLAT

PLAT --> CTRL: agenda

deactivate PLAT

CTRL -> AGENDA : getTaskByNameAndGreenSpace(taskParkName, taskName)

activate AGENDA

ref over AGENDA

Get Task By Name and GreenSpace

end

AGENDA --> CTRL : task

deactivate AGENDA

CTRL -> CTRL : assignTeam(team,task)

activate CTRL

ref over CTRL

Assign Team Task

end

CTRL --> CTRL : true/false

deactivate CTRL

alt assignTeam == true

CTRL -> CTRL : sendEmailTeam(team, msg)

activate CTRL

ref over CTRL

Send Email By Team

end

CTRL --> CTRL : true/false

deactivate CTRL

end

CTRL --> UI : true/false

deactivate CTRL

UI --> GSM	 : displays operation success

deactivate UI

deactivate GSM
@enduml