@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignTeamAgendaController" as CTRL
participant "agenda\n:Agenda" as AGENDA
participant "tasksAgenda\n:TasksAgenda" as TASKAGENDA
participant "taskAgenda\n:TaskAgenda" as TASK

autonumber 43

--> CTRL : assignTeamTask(team,taskAgenda)

autonumber 43.1
group Assign Team Task

activate CTRL

CTRL -> AGENDA : assignTeamTask(team,taskAgenda)

activate AGENDA

AGENDA -> TASKAGENDA : assignTeamTask(team,taskAgenda)

activate TASKAGENDA

loop for each taskAgenda in listTaskAgenda[in TasksAgenda]

TASKAGENDA -> TASK : equalsTask(taskAgenda)

activate TASK

TASK --> TASKAGENDA : true/false

deactivate TASK

alt equalsTask == true

TASKAGENDA -> TASK : updateTeam(team)

activate TASK

TASK --> TASKAGENDA : true/false

deactivate TASK

end

end

TASKAGENDA --> AGENDA : true/false

deactivate TASKAGENDA

AGENDA --> CTRL : true/false

deactivate AGENDA

end

autonumber 44

<--CTRL : true/false

deactivate CTRL
@enduml