@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":TaskAgendaMapper" as TEAMMP
participant "listTaskAgenda\n:List<TaskAgenda>" as TEAMLIST
participant "listTaskAgendaDto\n:List<TaskAgendaDto>" as LSTEAMDTO
participant "objDto\n:TaskAgendaDto" as DTOTEAM

autonumber 13

--> TEAMMP : toDTO(listTaskAgenda)

autonumber 13.1

activate TEAMMP

group To DTO List

TEAMMP --> LSTEAMDTO** : create()

loop for each object in listTaskAgenda

TEAMMP -> TEAMLIST : get(i)

activate TEAMLIST

TEAMLIST --> TEAMMP : obj

deactivate TEAMLIST

TEAMMP -> TEAMMP : objDto = toDTO(obj)

activate TEAMMP

TEAMMP --> DTOTEAM** : create(obj)

deactivate TEAMMP

TEAMMP -> LSTEAMDTO : add(objDto)

activate LSTEAMDTO

LSTEAMDTO --> TEAMMP : true/false

deactivate LSTEAMDTO

end

end

autonumber 14

<-- TEAMMP : listTaskAgendaDto

deactivate TEAMMP
@enduml
