@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "agenda\n:Agenda" as AGENDA
participant "tasksAgenda\n:TasksAgenda" as TASKSAGENDA
participant "taskAgenda\n:TaskAgenda" as TASK
participant "taskToDoList\n:TaskToDoList" as TODO

autonumber 41

--> AGENDA : getTaskByReference(taskReference)

autonumber 41.1

activate AGENDA

group Get Task By Reference

AGENDA -> TASKSAGENDA : getTaskByReference(taskReference)

activate TASKSAGENDA

loop for each TaskAgenda in taskAgendaList[in TaskAgenda]

TASKSAGENDA -> TASK : verifyHasTaskReference(taskReference)

activate TASK

TASK -> TODO : hasRef(ref)

activate TODO

TODO --> TASK : true/false

deactivate TODO

TASK --> TASKSAGENDA :true/false

deactivate TASK

end

TASKSAGENDA -> AGENDA : taskAgenda

deactivate TASKSAGENDA

end

autonumber 42

<--AGENDA : taskAgenda

deactivate AGENDA
@enduml