@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype orto

skinparam classAttributeIconSize "1"

package "UI" <<Folder>> {
    class RegisterEntryToDoListUI {
    }
}


package "Controller" <<Folder>> {

    class RegisterEntryToDoListController {
        + RegisterEntryToDoListController(greenSpaceRepository, collaboratorRepository, taskRepository, toDoList)
        + getGreenSpace()
        + registerEntryToDoList(greenSpaceName,taskDescription,urgency,duration)
        - getGSMFromSession()
    }

}

'left to right direction
package "Domain" <<Folder>> {

    package "Domain.Application" <<Folder>> {

        class ApplicationSession
        {
            + static getInstance()
            + getCurrentSession()
        }

        class UserSession
        {
            + getUserEmail()
        }
    }

    package "Domain.Model" <<Folder>> {

        interface GreenSpace {
            + getName()
            + getArea()
            + getAddress()
            + hasName(greenSpaceName)
        }

        class Garden{
            - String name
            - int area
            - Address

            + Garden(name,area,streetName,postCode)
            + getName()
            + getArea()
            + getAddress()
            + hasName(greenSpaceName)
        }

        class MediumPark{
            - String name
            - int area
            - Address

            + getName()
            + getArea()
            + getAddress()
            + MediumPark(name,area,streetName,postCode)
            + hasName(greenSpaceName)
        }

        class LargePark{
            - String name
            - int area
            - Address

            + getName()
            + getArea()
            + getAddress()
            + LargePark(name,area,streetName,postCode)
            + hasName(greenSpaceName)
        }

        class Collaborator {
                -String name
                -Job job
                -Date dateOfBirth
                -Date admissionDate
                -Address address
                -Document document
                -String phoneNumber
                -String email
                -int taxpayer

                + Collaborator(name, job, dateOfBirth, admissionDate, address, document, phoneNumber, email, taxpayer)
        }

        class Task {
            - String taskDescription

            + Task(taskDescription)
            + hasDescription(taskDescription)
        }

        class TaskToDoList {
            - GreenSpace greenSpace
            - Task task
            - String urgency
            - int duration
            - String status

            + TaskToDoList(greenSpace, task, urgency, duration)
            - validateTaskToDoList();
        }

        class GreenSpaceManager {
            - List<GreenSpace> managesGreenPlaceList

            + GreenSpaceManager()
            + getGreenSpace()
        }

        class ToDoList{

            + ToDoList()
            + registerEntryToDoList(greenSpace,task,urgency,duration)
            - addListTaskToDoList(taskToDoList)
            - validateToDoList()
        }

    }

    package "Domain.Repository" <<Folder>> {

        class Repositories {

            - Repositories()
            + getInstance() : Repositories
            + getGreenSpaceRepository()
            + getCollaboratorRepository()
            + getTaskRepository();
            + getToDoList()
        }

        class CollaboratorRepository {

            + getCollaboratorByEmail(greenSpace)
        }

        class GreenSpaceRepository {

            + getGreenSpaceByName(greenSpaceName)
        }

        class TaskRepository {

            + getAllTaskDescriptions()
        }
    }
}

'-------------------Instance-------------------
Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

'-------------------UI-------------------
RegisterEntryToDoListUI ..> RegisterEntryToDoListController

'-------------------Controller-------------------
RegisterEntryToDoListController ...> Repositories : repositories
RegisterEntryToDoListController ...> ApplicationSession
RegisterEntryToDoListController ...> UserSession
RegisterEntryToDoListController ...> GreenSpaceRepository
RegisterEntryToDoListController ...> CollaboratorRepository
RegisterEntryToDoListController ...> TaskRepository
RegisterEntryToDoListController ...> Collaborator
RegisterEntryToDoListController ...> GreenSpace
RegisterEntryToDoListController ...> ToDoList
RegisterEntryToDoListController ...> Task
RegisterEntryToDoListController ...> TaskToDoList
RegisterEntryToDoListController ...> GreenSpaceManager

'-------------------ApplicationSession-------------------
ApplicationSession --> "1" UserSession : userSession

'-------------------Repositories-------------------
Repositories --> "1" GreenSpaceRepository : GreenSpaceRepository
Repositories ---> "1" CollaboratorRepository : CollaboratorRepository
Repositories --> "1" ToDoList : ToDoList
Repositories --> "1" TaskRepository : TaskRepository

'-------------------CollaboratorRepository-------------------
CollaboratorRepository "1"  -> "*" Collaborator : collaborator

'-------------------GreenSpaceRepository-------------------
GreenSpaceRepository "1" -> "*" GreenSpace : greenSpace

'-------------------TaskRepository-------------------
TaskRepository "1" -> "*" Task : task

'-------------------Collaborator-------------------
Collaborator <|-- GreenSpaceManager

'-------------------GreenSpaceManager-------------------
GreenSpaceManager "1..*" <-- "1..*" TaskToDoList : created by
GreenSpaceManager "1..*" <-- "1..*" GreenSpace : managed by

'-------------------GreenSpace-------------------
GreenSpace <|-- Garden
GreenSpace <|-- MediumPark
GreenSpace <|-- LargePark

'-------------------ToDoList-------------------
ToDoList "1" --> "*" TaskToDoList : taskTdl

'-------------------TaskToDoList-------------------
TaskToDoList "1..*" --> "1" GreenSpace : greenSpace
TaskToDoList "1..*" --> "1" Task : task

@enduml