@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "toDoList\n:ToDoList" as TDL
participant "taskTdl\n:TaskToDoList" as TTDL

autonumber 45
-> TDL: registerEntryToDoList(greenSpace,task,urgency,duration)

autonumber 45.1
activate TDL
    group Register Entry


        TDL -> TDL: generateUniqueReference()
        activate TDL
        TDL --> TDL: taskRef
        deactivate TDL

        TDL -> TTDL**: create(greenSpace,task,urgency,duration,taskRef)

    activate TTDL

        TTDL -> TTDL: validateTask()
    activate TTDL

        TTDL --> TTDL: true/false
    deactivate TTDL

        TTDL --> TDL : taskTdl
    deactivate TTDL

        TDL -> TDL: addTaskToDoList(taskTdl)
    activate TDL

        TDL -> TDL: validateTaskToDoList(taskTdl)
    activate TDL

        TDL --> TDL : true/false
    deactivate TDL

        TDL --> TDL : true/false
    deactivate TDL
    end

    autonumber 46
    <-- TDL : taskTdl
deactivate TDL


@enduml